/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(16) SensorData_t_sensorData_t;
typedef struct _SensorData_t {
    uint8_t sensorType;
    SensorData_t_sensorData_t sensorData;
} SensorData_t;

typedef struct _TXData_t {
    uint8_t tx_count;
    uint16_t nodeId;
    uint8_t nodeType;
    uint8_t gatewayId;
    pb_size_t sensorsData_count;
    SensorData_t sensorsData[10];
} TXData_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_t_init_default                {0, {0, {0}}}
#define TXData_t_init_default                    {0, 0, 0, 0, 0, {SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default, SensorData_t_init_default}}
#define SensorData_t_init_zero                   {0, {0, {0}}}
#define TXData_t_init_zero                       {0, 0, 0, 0, 0, {SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero, SensorData_t_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_t_sensorType_tag              1
#define SensorData_t_sensorData_tag              2
#define TXData_t_tx_count_tag                    1
#define TXData_t_nodeId_tag                      2
#define TXData_t_nodeType_tag                    3
#define TXData_t_gatewayId_tag                   4
#define TXData_t_sensorsData_tag                 5

/* Struct field encoding specification for nanopb */
#define SensorData_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sensorType,        1) \
X(a, STATIC,   SINGULAR, BYTES,    sensorData,        2)
#define SensorData_t_CALLBACK NULL
#define SensorData_t_DEFAULT NULL

#define TXData_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tx_count,          1) \
X(a, STATIC,   SINGULAR, UINT32,   nodeId,            2) \
X(a, STATIC,   SINGULAR, UINT32,   nodeType,          3) \
X(a, STATIC,   SINGULAR, UINT32,   gatewayId,         4) \
X(a, STATIC,   REPEATED, MESSAGE,  sensorsData,       5)
#define TXData_t_CALLBACK NULL
#define TXData_t_DEFAULT NULL
#define TXData_t_sensorsData_MSGTYPE SensorData_t

extern const pb_msgdesc_t SensorData_t_msg;
extern const pb_msgdesc_t TXData_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_t_fields &SensorData_t_msg
#define TXData_t_fields &TXData_t_msg

/* Maximum encoded size of messages (where known) */
#define SensorData_t_size                        21
#define TXData_t_size                            243

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
