# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmessage.proto\"6\n\x0cSensorData_t\x12\x12\n\nsensorType\x18\x01 \x01(\r\x12\x12\n\nsensorData\x18\x02 \x01(\x0c\"u\n\x08TXData_t\x12\x10\n\x08tx_count\x18\x01 \x01(\r\x12\x0e\n\x06nodeId\x18\x02 \x01(\r\x12\x10\n\x08nodeType\x18\x03 \x01(\r\x12\x11\n\tgatewayId\x18\x04 \x01(\r\x12\"\n\x0bsensorsData\x18\x05 \x03(\x0b\x32\r.SensorData_tb\x06proto3'
)




_SENSORDATA_T = _descriptor.Descriptor(
  name='SensorData_t',
  full_name='SensorData_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorType', full_name='SensorData_t.sensorType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorData', full_name='SensorData_t.sensorData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=71,
)


_TXDATA_T = _descriptor.Descriptor(
  name='TXData_t',
  full_name='TXData_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_count', full_name='TXData_t.tx_count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='TXData_t.nodeId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeType', full_name='TXData_t.nodeType', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gatewayId', full_name='TXData_t.gatewayId', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorsData', full_name='TXData_t.sensorsData', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=190,
)

_TXDATA_T.fields_by_name['sensorsData'].message_type = _SENSORDATA_T
DESCRIPTOR.message_types_by_name['SensorData_t'] = _SENSORDATA_T
DESCRIPTOR.message_types_by_name['TXData_t'] = _TXDATA_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorData_t = _reflection.GeneratedProtocolMessageType('SensorData_t', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA_T,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:SensorData_t)
  })
_sym_db.RegisterMessage(SensorData_t)

TXData_t = _reflection.GeneratedProtocolMessageType('TXData_t', (_message.Message,), {
  'DESCRIPTOR' : _TXDATA_T,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:TXData_t)
  })
_sym_db.RegisterMessage(TXData_t)


# @@protoc_insertion_point(module_scope)
